FROM centos:6.6

MAINTAINER Liu Yin <liuy@pingcap.com>

COPY epel-apache-maven.repo /etc/yum.repos.d/epel-apache-maven.repo

RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -

RUN yum makecache \
	&& yum update -y \
	&& yum install -y tar wget git which file centos-release-scl psmisc \
	&& yum install -y make devtoolset-4-gcc-c++ python27 gcc gcc-c++ libstdc++-static \
	&& yum install -y openssh-server openssl-devel \
	&& yum install -y java-1.8.0-openjdk \
	&& yum install -y nodejs \
	&& yum install -y apache-maven \
	&& yum clean all

RUN curl -L https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.sh -o cmake-3.10.0-Linux-x86_64.sh \
	&& chmod +x ./cmake-3.10.0-Linux-x86_64.sh \
	&& ./cmake-3.10.0-Linux-x86_64.sh --skip-license --prefix=/usr \
	&& cmake --version \
	&& rm -rf ./cmake-3.10.0-Linux-x86_64.sh

ENV GOLANG_VERSION 1.9.2
ENV GOLANG_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_VERSION.linux-amd64.tar.gz
ENV GOLANG_DOWNLOAD_SHA256 de874549d9a8d8d8062be05808509c09a88a248e77ec14eb77453530829ac02b

RUN curl -fsSL "$GOLANG_DOWNLOAD_URL" -o golang.tar.gz \
	&& echo "$GOLANG_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
	&& tar -C /usr/local -xzf golang.tar.gz \
	&& rm golang.tar.gz

ENV GOPATH /go
ENV GOROOT /usr/local/go
ENV PATH $GOPATH/bin:$GOROOT/bin:$PATH

RUN go get golang.org/x/tools/go/gcimporter15 \
	&& go get github.com/golang/lint/golint

RUN adduser jenkins --uid 1000 \
	&& echo "jenkins:jenkins" | chpasswd

RUN su jenkins -c "curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --default-toolchain nightly-2018-04-06 -y" \
	&& su jenkins -c "/home/jenkins/.cargo/bin/rustup default nightly-2018-04-06"

# cache dep package
RUN su jenkins -c "curl -L https://github.com/pingcap/tikv/archive/master.tar.gz -o /home/jenkins/master.tar.gz" \
	&& su jenkins -c "curl -L http://download.pingcap.org/rustfmt-v0.6.0-linux-amd64.tar.gz -o /home/jenkins/rustfmt-v0.6.0-linux-amd64.tar.gz" \
	&& su jenkins -c "cd /home/jenkins && tar xf master.tar.gz && cd tikv-master && /home/jenkins/.cargo/bin/cargo fetch" \
	&& su jenkins -c "cd /home/jenkins && tar xzf rustfmt-v0.6.0-linux-amd64.tar.gz -C /home/jenkins/.cargo/bin --strip-components=1" \
	&& su jenkins -c "cd /home/jenkins && rm -rf master.tar.gz tikv-master rustfmt-v0.6.0-linux-amd64.tar.gz"

RUN sed -i 's|session    required     pam_loginuid.so|session    optional     pam_loginuid.so|g' /etc/pam.d/sshd \
	&& mkdir -p /var/run/sshd \
	&& ssh-keygen -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N "" -q \
	&& ssh-keygen -t dsa -b 1024 -f /etc/ssh/ssh_host_dsa_key -N "" -q

RUN mkdir -p /home/pingcap && cd /home/pingcap \
	&& curl -fsSL "http://pingcap-dev.ufile.ucloud.com.cn/jenkins/jenkins-slave-docker-sqllogictest.tar.gz" -o jenkins-slave-docker-sqllogictest.tar.gz \
	&& tar xzvf jenkins-slave-docker-sqllogictest.tar.gz \
	&& rm -rf jenkins-slave-docker-sqllogictest.tar.gz 

RUN cd /home/jenkins \
	&& curl -fsSL "http://pingcap-dev.ufile.ucloud.com.cn/jenkins/jenkins-slave-docker-m2.tar.gz" -o jenkins-slave-docker-m2.tar.gz \
	&& tar xzvf jenkins-slave-docker-m2.tar.gz \
	&& rm -rf jenkins-slave-docker-m2.tar.gz

COPY .gitcookies /home/jenkins/.gitcookies

COPY bin /home/jenkins/bin

RUN chown jenkins:jenkins /home/jenkins/.gitcookies \
	&& chmod 0600 /home/jenkins/.gitcookies \
	&& su jenkins -c "git config --global http.cookiefile /home/jenkins/.gitcookies" \
	&& chown -R jenkins:jenkins /home/jenkins/bin

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]

