- name: generate ifcfg-eth0 conf
  template:
    src: "ifcfg-eth0.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-eth0"
    mode: "0644"
    owner: "root"
    group: "root"

- name: restart network service
  systemd:
    state: restarted
    daemon_reload: yes
    name: network
